version = "3.8.3"
runner.dialect = scala3

maxColumn = 120

align.preset = none
align.openParenCallSite = false
align.openParenDefnSite = false

newlines.source = keep
docstrings.style = Asterisk
docstrings.wrap = no

rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers, Imports]
rewrite.scala3.convertToNewSyntax = true
rewrite.scala3.removeOptionalBraces = true
rewrite.scala3.insertEndMarkerMinLines = 30

rewrite.redundantBraces.stringInterpolation = true

rewrite.imports.groups = [["javax?\\..*"], ["scala\\..*"], [".*"]]
rewrite.imports.sort = scalastyle

project.git = true
